### ISSUE TITLE
Does not appear in mirror

### ISSUE THREAD

**Issue by wickles** [theepicsnail/Marker#12] opened 2021-01-06 23:58 UTC
Using the SDK3 marker only shows up in occasional bits in the mirror if at all. My marker stuff is all in the FX layer, which seems to be the only one that it works on. Is there any way to fix this?

**Comment by chibiskuld** [comment] 2021-01-07 14:20
I haven't confirmed it yet, but I've been told the issue is because of the shader. The person that reported that, stated it's because it's getting reversed in the mirror, and the shader needs to be set to cull off, to render double sided.

**Comment by wickles** [comment] 2021-01-18 23:48
I just tested this by using Poiyomi with backface culling off and it does fix the problem. The shaders shipped as part of the marker package do not have an option to disable backface culling as far as I can tell.

**Comment by LakesGeek** [comment] 2021-03-08 23:42
Thanks, that works for me. I set the RainbowTrail (in my case) shader to poiyomi , picked vertical rainbow for the main texture and basic emission to 0.4, this gives similar results, and with cull set to none... works in mirrors

I'm guessing for people with custom shaders of it'll downgrade to an unlit standard shader so no good in the dark but otherwise fine. I encounter mirrors more often than too-dark environments

**Comment by chibiskuld** [comment] 2021-06-14 00:26
was fixed in 3.1.1 with new shader

**Closed as completed** 2021-06-14 00:26 UTC
